apiVersion: v1
kind: Service
metadata:
  namespace: ${namespace}
  name: ${name}
%{ if backendconfig != "" }
  annotations:
    cloud.google.com/backend-config: '{"default": "${backendconfig}"}'
%{ endif }
spec:
  type: ${type}
  selector:
    app: ${app_name}
  ports:
    - port: 80
      targetPort: ${target_port}