apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: ${namespace}
  name: ingress-nginx-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    type: HTTP
    requestPath: /healthz
  securityPolicy:
    name: "${armor_policy_name}"